[project]
name = "multi-sig-wallet"
description = "A multi-signature wallet smart contract for the Stacks blockchain"
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.multi-sig-wallet]
path = "contracts/multi-sig-wallet.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
